                                  --ASSIGNMENT2--
SELECT * FROM CUSTOMER

SELECT * FROM EMPLOYEE

SELECT * FROM [ORDER ]

SELECT * FROM PRODUCT

SELECT * FROM SHIP

SELECT * FROM CUSTOMER WHERE COUNTRY = 'GERMANY'

SELECT CONCAT([EMP-FIRST-NAME],' ' ,[EMP-LAST-NAME]) AS EMPLOYENAME FROM EMPLOYEE

SELECT * FROM CUSTOMER WHERE [FAX-NUMBER] != 'NULL'

SELECT * FROM CUSTOMER WHERE [FIRST-NAME] LIKE '_U%'

SELECT * FROM ORDERITEM WHERE [UNIT-PRICE] BETWEEN 10 AND 20
SELECT * FROM ORDERITEM WHERE [UNIT-PRICE] > 10 AND [UNIT-PRICE] < 20

SELECT * FROM [ORDER ] WHERE [SHIPPING-DATE] !='' ORDER BY [SHIPPING-DATE]

SELECT * FROM [ORDER ] WHERE ([SHIPPING-DATE] BETWEEN '2022-01-01' AND '2022-08-08') and ([SHIP-NAME]='La corne dabondance') 

SELECT * FROM PRODUCT WHERE SUPPLIERS ='EXOTIC LIQUIDS'

SELECT AVG(QUANTITY) AS AVERAGE,[PRODUCT-ID] FROM ORDERITEM GROUP BY [PRODUCT-ID]

SELECT [SHIPPING-COMPANY],[SHIP-STATUS] FROM SHIP WHERE [SHIP-STATUS]='OPERATIONAL'

SELECT CONCAT([EMP-FIRST-NAME],' ' ,[EMP-LAST-NAME]) AS EMPLOYENAME, MANAGER FROM EMPLOYEE

CREATE PROCEDURE SPORDERBYID
@ID INT
AS 
BEGIN
SELECT ORDERITEM.[ORDER-ID],PRODUCT.[PRODUCT-NAME],PRODUCT.CATEGORY,[ORDER ].[DISCOUNT-PRICE] FROM ORDERITEM
INNER JOIN [ORDER ] ON [ORDER ].[ORDER-ID]=ORDERITEM.[ORDER-ID]
INNER JOIN PRODUCT ON PRODUCT.[PRODUCT-ID]=ORDERITEM.[PRODUCT-ID] 
WHERE ORDERITEM.[ORDER-ID]= @ID
END

SELECT PRODUCT.SUPPLIERS,PRODUCT.[UNIT-PRICE] AS TOTALPRICE ,SHIP.[SHIPPING-COMPANY] FROM PRODUCT
INNER JOIN SHIP ON SHIP.[SHIP-NAME]=PRODUCT.[SHIP-NAME]
WHERE PRODUCT.SUPPLIERS = 'EXOTIC LIQUIDS' AND PRODUCT.[UNIT-PRICE] >10

SELECT PRODUCT.SUPPLIERS,PRODUCT.[UNIT-PRICE] AS TOTALPRICE ,SHIP.[SHIPPING-COMPANY] FROM PRODUCT
INNER JOIN SHIP ON SHIP.[SHIP-NAME]=PRODUCT.[SHIP-NAME]
WHERE PRODUCT.SUPPLIERS = 'EXOTIC LIQUIDS' AND PRODUCT.[UNIT-PRICE] >50



SPORDERBYID 403

