SELECT * FROM [ORDER]
SELECT * FROM CUSTOMER
SELECT* FROM ORDERITEM
SELECT * FROM PRODUCT
SELECT * FROM CUSTOMER WHERE COUNTRY LIKE '[AI]%'
SELECT  [FIRST-NAME] AS CUSTOMERNAME FROM CUSTOMER WHERE [FIRST-NAME] LIKE '__I%'